### ISSUE TITLE
Submitting Invoice Number with Transaction

### ISSUE THREAD

**Issue by tclancy** [drewisme/authorizesauce#33]
In light of #5 and #24, I'm guessing you don't have an interest in supporting this, but is there a simple way for me to hack this in? [It looks like](https://developer.authorize.net/api/reference/) I'd need to add an `order` that has an `invoiceNumber` property. Rather than add a whole `Order` class to `data.py`, can I get away with calling [`_add_params`](https://github.com/jeffschenck/authorizesauce/blob/master/authorize/apis/transaction.py#L90) directly and passing in `{"order": {"invoiceNumber": "xyz"}}`?

**Comment by tclancy** [comment]
In case it helps anyone, I cheated and modified my `CreditCard` object like this:

```
self.credit_card._client._transaction.base_params["x_invoice_num"] = self.cleaned_data["patient_id"]
```

**Comment by danielatdattrixdotcom** [comment]
The above is for non-CIM captures. If you have a CIM saved card and want to add the same what you want is the following:

```python
card_to_charge = client.saved_card('1234567|5587547')
card_to_charge._client._customer.transaction_options += '&x_invoice_num=%s' % invoice_number
```
