### ISSUE TITLE
User Authentication Failed

### ISSUE THREAD

**Issue by chrisburgin95** [drewisme/authorizesauce#38]
``` E00007: User authentication failed due to invalid authentication values. ```

That is the error I am receiving, the default test information that is included works well but when i generate my own transaction key and API Login key I receive the above error.

My account is in test mode.

Has anyone else experienced this problem?

**Comment by drewisme** [comment]
Ensure you have an account with https://sandbox.authorize.net/ if you are testing in debug mode. Setting your production account to test mode does not make it available for testing in sandbox.
