### ISSUE TITLE
<urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by livingmonkey** [drewisme/authorizesauce#40]
I have an implementation of authorizesauce that's been working for months and suddenly I'm getting this error. I reverted my code to my last known working configuration and it still errors the same. I'm not understanding what it's complaining about.

The error is :<urlopen error [Errno -2] Name or service not known>
 	/usr/lib/python2.7/urllib2.py in do_open, line 1184
and it seems to be occurring after the transaction is set

```
try:
   transaction = client.card(cc).capture(20.00) 
except..
..
except..
else:
    saved_card = client.card(cc).save()
```

client.card(cc).save() takes it into
> /usr/local/lib/python2.7/dist-packages/authorize/apis/customer.py(79)create_saved_profile()
-> response = self._make_call('CreateCustomerProfile', profile, 'none')
and then eventually into 
> /usr/local/lib/python2.7/dist-packages/suds/client.py(581)invoke()
-> result = self.send(soapenv)
> /usr/local/lib/python2.7/dist-packages/suds/client.py(586)send()
-> def send(self, soapenv):
> /usr/local/lib/python2.7/dist-packages/suds/client.py(594)send()
>self.location()

self.location outputs: https://oce-ex-cert-api.authorize.net/soap/v1/Service.asmx
which appears to be invalid and is maybe why this method fails?
it continues into:
 /usr/local/lib/python2.7/dist-packages/suds/client.py(608)send()
-> request = Request(location, soapenv)
> /usr/local/lib/python2.7/dist-packages/suds/client.py(613)send()
-> reply = self.options.transport.send(request)
> /usr/local/lib/python2.7/dist-packages/suds/transport/https.py(66)send()
-> return HttpTransport.send(self, request)
> /usr/local/lib/python2.7/dist-packages/suds/transport/http.py(77)send()
->u2request = urllib2.Request(url, msg, headers)
url is that same location above which doesnt return anything in a browser:
'https://oce-ex-cert-api.authorize.net/soap/v1/Service.asmx'
> /usr/lib/python2.7/urllib2.py(210)__init__()
-> self.headers = {}
(Pdb) self.data
'<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://api.authorize.net/soap/v1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><ns0:Body><ns1:CreateCustomerProfile><ns1:merchantAuthentication><ns1:name>9XbVU3pNB2u</ns1:name><ns1:transactionKey>9999b425h9GskTHR</ns1:transactionKey></ns1:merchantAuthentication><ns1:profile><ns1:merchantCustomerId>7701676e7a5f4895ac4c</ns1:merchantCustomerId><ns1:paymentProfiles><ns1:CustomerPaymentProfileType><ns1:customerType>individual</ns1:customerType><ns1:billTo><ns1:firstName>dennis 1</ns1:firstName></ns1:billTo><ns1:payment><ns1:creditCard><ns1:cardNumber>4111111111111111</ns1:cardNumber><ns1:expirationDate>2100-12</ns1:expirationDate><ns1:cardCode>222</ns1:cardCode></ns1:creditCard></ns1:payment></ns1:CustomerPaymentProfileType></ns1:paymentProfiles></ns1:profile><ns1:validationMode>none</ns1:validationMode></ns1:CreateCustomerProfile></ns0:Body></SOAP-ENV:Envelope>'

```
214  ->	        if origin_req_host is None:
215  	            origin_req_host = request_host(self)
```
request_host(self) outputs> 'oce-ex-cert-api.authorize.net'
-> self.unverifiable = unverifiable
(Pdb) unverifiable
False
> /usr/local/lib/python2.7/dist-packages/suds/transport/http.py(82)send()
-> fp = self.u2open(u2request)
(Pdb) self.u2open(u2request)
*** URLError: <urlopen error [Errno -2] Name or service not known>
> /usr/local/lib/python2.7/dist-packages/suds/transport/http.py(129)u2open()
-> if (sys.version_info < (3, 0)) and (self.u2ver() < 2.6):
(Pdb) sys.version_info
sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
> /usr/local/lib/python2.7/dist-packages/suds/transport/http.py(132)u2open()
-> return url.open(u2request, timeout=tm)
(Pdb) url.open(u2request, timeout=tm)
> /usr/lib/python2.7/urllib2.py(404)open()
(Pdb) req.__dict__
{'_Request__r_type': '//oce-ex-cert-api.authorize.net/soap/v1/Service.asmx', '_Request__original': 'https://oce-ex-cert-api.authorize.net/soap/v1/Service.asmx', 'data': '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://api.authorize.net/soap/v1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><ns0:Body><ns1:CreateCustomerProfile><ns1:merchantAuthentication><ns1:name>9XbVU3pNB2u</ns1:name><ns1:transactionKey>9999b425h9GskTHR</ns1:transactionKey></ns1:merchantAuthentication><ns1:profile><ns1:merchantCustomerId>f8943d36ac104fd8a8e0</ns1:merchantCustomerId><ns1:paymentProfiles><ns1:CustomerPaymentProfileType><ns1:customerType>individual</ns1:customerType><ns1:billTo><ns1:firstName>dennis 1</ns1:firstName></ns1:billTo><ns1:payment><ns1:creditCard><ns1:cardNumber>4111111111111111</ns1:cardNumber><ns1:expirationDate>2222-11</ns1:expirationDate><ns1:cardCode>123</ns1:cardCode></ns1:creditCard></ns1:payment></ns1:CustomerPaymentProfileType></ns1:paymentProfiles></ns1:profile><ns1:validationMode>none</ns1:validationMode></ns1:CreateCustomerProfile></ns0:Body></SOAP-ENV:Envelope>', '_tunnel_host': None, 'host': 'oce-ex-cert-api.authorize.net', 'origin_req_host': 'oce-ex-cert-api.authorize.net', 'headers': {'Soapaction': '"https://api.authorize.net/soap/v1/CreateCustomerProfile"', 'Content-type': 'text/xml; charset=utf-8'}, '_Request__fragment': None, 'timeout': 90, '_Request__r_host': '/soap/v1/Service.asmx', 'unredirected_hdrs': {'Content-length': '1080', 'Host': 'oce-ex-cert-api.authorize.net', 'User-agent': 'Python-urllib/2.7'}, 'unverifiable': False, 'type': 'https', 'port': None}

where it fails in /usr/lib/python2.7/urllib2.py(1222)https_open()
Can anyone help??

**Comment by jmichalicek** [comment]
I have actually been talking to authorize.net support about this issue.  The short version is that the wsdl is returning some incorrect URLs.  I was informed last week that they expect to have it fixed "early this week", but it clearly is not.  I did send my contact over there an email today to get an update, but there is still no hard date to fix it.

A workaround that they suggested is to copy the wsdl, change the bad url, and host it yourself.  That would of course mean changing authorizesauce to support that (unless I missed a parameter allowing us to specify different URLs).

The `oce-ex-cert-api.authorize.net` hostname coming from the wsdl is the problem part.  The dns for that does not resolve.

**Comment by drewisme** [comment]
Looks like Authorize.net resolved this on their end. Let me know if you still have an issue.
