### ISSUE TITLE
POST requests for transaction calls

### ISSUE THREAD

**Issue by elahmo** [drewisme/authorizesauce#43]
As per Authorize.net security updates, as of June 30, for transaction calls, the requests have to be sent via `POST`, not `GET`. We got an email from authorize.net taht we are making `GET` requests, and based on that, as well and `urlopen()` usage in the library, I assume the library relies on `GET` requests.

Is it possible to change this, so the transaction parameters are sent via `POST`? This will affect all users of the library since its a system wide change on their end, announced last year due to TLS requirements and PCI compliance. 

@drewisme seems to be the new project maintainer :) Could you maybe confirm this and give us some feedback regarding this?

**Comment by drewisme** [comment]
I received the same email from Authorize. I'm planning to look into refactoring the library to use `requests` instead of `urllib`. At the very least I'll update to use `POST`. I'll work to push something in a couple weeks

**Comment by drewisme** [comment]
Looks like @gsong  already took this on. I'll review and look to merge his pull request.

**Comment by gsong** [comment]
@elahmo See #42 for proposed changes to address this.

**Comment by ahopkins** [comment]
@gsong, @drewisme: How's this looking? POST submission in place? Any help needed?

**Comment by drewisme** [comment]
Hi @ahopkins, I just proposed a change to @gsong in #42.

**Comment by gsong** [comment]
See new PR #44

**Comment by drewisme** [comment]
Thanks for all the work @gsong! This is merged into v0.5.0.

This is released as v0.5.0 on PyPI. Enjoy!

**Comment by ahopkins** [comment]
Good work @gsong
