### ISSUE TITLE
AuthorizeConnectionError

### ISSUE THREAD

**Issue by wongyikfei** [drewisme/authorizesauce#46]
Hi, I'm receiving this error when trying to test for a transaction in debug mode under sandbox environment. The production environment works just fine, only the sandbox keep showing up the error. As there are only a few documents about this error, I'm not really sure what is going wrong here. I would like to ask under what condition might this error happen? My production and sandbox environment basically share the same code and I'm pretty sure my sandbox account is configured correctly... the problem occurs after we updated authorizesauce to 5.0

**Comment by drewisme** [comment]
Can you provide some more details?

- What is the full response from AuthNet?
- Can you share the code that is throwing the error with credentials masked?

**Comment by wongyikfei** [comment]
The error I'm getting is "<urlopen error [Errno 54] Connection reset by peer>"

traceback:
`Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/myfolder/apis.py", line 1768, in api_submit
    cc, address=cc_address, email=email).capture(deposit_price)
  File "/Library/Python/2.7/site-packages/authorize/client.py", line 131, in capture
    amount, self.credit_card, self.address, self.email)
  File "/Library/Python/2.7/site-packages/authorize/apis/transaction.py", line 136, in capture
    return self._make_call(params)
  File "/Library/Python/2.7/site-packages/authorize/apis/transaction.py", line 84, in _make_call
    raise AuthorizeConnectionError(e)
AuthorizeConnectionError: <urlopen error [Errno 54] Connection reset by peer>`

The code:
`client = authorize.AuthorizeClient(
      app.config['AUTHORIZE_NET_ACCOUNT'],
      app.config['AUTHORIZE_NET_KEY'])

  cc = authorize.CreditCard(credit_card_num, validate_year, validate_month,
                            secure_code, credit_card_holder)
  cc_address = authorize.Address(street=street_address,
                                 city=city,
                                 state=state,
                                 zip_code=zip_code)
  transaction = client.card(
      cc, address=cc_address, email=email).capture(deposit_price)`

I keep receiving connection error from the above code, only in sandbox condition, for the production it works fine.

**Comment by drewisme** [comment]
It doesn't look like the client is in sandbox mode. Can you try the following?
`client = authorize.AuthorizeClient(
	app.config['AUTHORIZE_NET_ACCOUNT'],
	app.config['AUTHORIZE_NET_KEY'],
	debug=True)`

**Comment by wongyikfei** [comment]
I tried both, with and without <debug=True>, both return the same result

**Comment by wongyikfei** [comment]
The debug code worked just fine for over an year. The problem suddenly appears when we upgrade authorizeSauce from 4.1 to 5.0.

**Comment by drewisme** [comment]
Can you print "self.url" and "params" before line 79 in "/Library/Python/2.7/site-packages/authorize/apis/transaction.py"? I can try to reproduce the issue.

**Comment by wongyikfei** [comment]
self.url: https://test.authorize.net/gateway/transact.dll

params: x_login=6f6qM7F3&x_zip=47906&x_card_num=6011000000000012&x_amount=2000.00&x_card_code=321&x_tran_key=3Ln22J6Y4Laa47s7&x_city=West+Lafayette&x_country=US&x_version=3.1&x_state=IN&x_first_name=asd&x_address=210+W+Wood+St%2C+Apt+4&x_exp_date=07-2022&x_email=wongyikfei%40gmail.com&x_delim_data=TRUE&x_delim_char=%3B&x_type=AUTH_CAPTURE&x_test_request=FALSE

**Comment by drewisme** [comment]
I tested this in Python 2.7.13 and Python 3.4.2 with no issues. Here's the response as expected:
`1;1;1;This transaction has been approved.;D4YVGJ;Y;40004993314;;;2000.00;CC;auth_capture;;asd;;;210 W Wood St, Apt 4;West Lafayette;IN;47906;US;;;wongyikfei@gmail.com;;;;;;;;;;;;;;F7EDD54EC4625B881C6F1373E2A0C4F1;P;2;;;;;;;;;;;XXXX0012;Discover;;;;;;;;;;;;;;;;;`


Seems like you might have a connection issue with "https://test.authorize.net/". Do you have any manual overrides for this domain?

**Comment by drewisme** [comment]
This may provide some insight:
https://community.developer.authorize.net/t5/Integration-and-Testing/AIM-Transactions-with-Java-SDK-SSL-TLS-issue/td-p/13114

**Comment by wongyikfei** [comment]
I believe that I did not have any manual overrides for the domain, but I think I start to figure out what's going wrong here.

I'm using Python 2.7.10, it returned the error. But when I tried 2.7.11 in my virtual environment, the code has run successfully. It seems that It might be something related to python version.
