### ISSUE TITLE
Authorize.net error code 66

### ISSUE THREAD

**Issue by dennben78** [drewisme/authorizesauce#47]
Hi I am using authorizesauce - been using it for awhile and started getting errors on 7/7/17. 
They are not recorded in authorize.net at all, they are denying my transaction.
The response returned is this:
[Mon Jul 10 23:10:13 2017] [error] Error response code returned from API. <class 'authorize.exceptions.AuthorizeResponseError'> - This transaction cannot be accepted for processing. full_response={'cvv_response': '', 'authorization_code': '', 'response_code': '3', 'amount': '120.00', 'transaction_type': 'auth_capture', 'avs_response': 'P', 'response_reason_code': '66', 'response_reason_text': 'This transaction cannot be accepted for processing.', 'transaction_id': '0'}

I have no idea what changed, or why I would be the only one getting this error -- but I can't seem to find any one else complaining about it on the web.

I did happen to notice that authorize.net changed their API code but it's not supposed to have any effect on past implementations.
(see change log for API changes on 7/7/17 here: http://developer.authorize.net/api/changes/)

Note: my first transaction after 7/7 was actually on 7/10 which is when i started having this issue of not being able to process credit card payments. And Yes, I'm still on https.

Any insight, suggestions or tips are appreciated!

I'm currently working on developing my own solution, but I'd like to stay using authorizeSauce - it's been very reliable up til now.

Thanks!

**Comment by drewisme** [comment]
Here's the article about error code:
https://support.authorize.net/authkb/index?page=content&id=A612&actp=LIST

Are you using the most recent version 0.5.0? If not, you need to upgrade. Authorize.net stopped supporting HTTP GET for AIM transactions. This was updated to HTTP POST in 0.5.0.

If you still have an issue on the most recent version can you provide some details?

- Python version
- Sandbox or Production
- If this is happening on sandbox, can you provide your request payload?

**Comment by dennben78** [comment]
Yeah I upgraded to authorizesauce .5.0 and no change.
python ==2.7.5
SANDBOX and PRODUCTION are affected the same way.

What's the easiest way to capture the payload?

**Comment by drewisme** [comment]
Looks like this might be related to #46.

> Can you print "self.url" and "params" before line 79 in "/Library/Python/2.7/site-packages/authorize/apis/transaction.py"? I can try to reproduce the issue.

**Comment by dennben78** [comment]
UPDATE: before you had asked about the version, I had thought I was at the tip but I was at 0.4 for whatever reason I didn't see .0.5 til you mentioned it. So originally I was on 0.3 and upgraded to .4 with no change. I upgraded to .5 and now SANDBOX works, but PRODUCTION is still broken.

Here is the payload info you requested:
LIVE TRANSACTION
URL: 'https://secure.authorize.net/gateway/transact.dll'

params:
x_login=5E9JxJqXXXX&x_type=AUTH_CAPTURE&x_card_num=4111111111111111&x_amount=30.00&x_card_code=154&x_tran_key=7V2y5xXXXXXXXXXX&x_version=3.1&x_first_name=denny+2&x_exp_date=12-2021&x_delim_data=TRUE&x_delim_char=%3B&x_test_request=FALSE'

TEST TRANSACTION
URL 'https://test.authorize.net/gateway/transact.dll'
params
'x_login=9XbVU3pXXXX&x_type=AUTH_CAPTURE&x_card_num=4111111111111111&x_amount=30.00&x_card_code=555&x_tran_key=9999b425h9GXXXXX&x_version=3.1&x_first_name=denny+2&x_exp_date=12-2018&x_delim_data=TRUE&x_delim_char=%3B&x_test_request=TRUE'

**Comment by drewisme** [comment]
What is the response from production? Production will only work with a valid credit card.

**Comment by dennben78** [comment]
[Thu Jul 13 20:00:27 2017] [error] Error response code returned from API. <class 'authorize.exceptions.AuthorizeResponseError'> - This transaction cannot be accepted for processing. full_response={'cvv_response': '', 'authorization_code': '', 'response_code': '3', 'amount': '15.00', 'transaction_type': 'auth_capture', 'avs_response': 'P', 'response_reason_code': '66', 'response_reason_text': 'This transaction cannot be accepted for processing.', 'transaction_id': '0'}


It is working in my sandbox fully if I mimic production settings completely. WHat version of six is required? There must be some conflict somewhere in my pip requirements?
This is pip freeze of my production environment:
apns==2.0.1
AuthorizeSauce==0.5.0
chardet==2.2.1
Django==1.7
django-crontab==0.6.0
django-extensions==1.6.1
django-inspect==0.4.1
django-messages-extends==0.4
django-ssl-redirect==1.0
djangorestframework==2.4.4
djrill==1.3.0
docopt==0.6.1
docutils==0.7
egenix-mx-base==3.1.3
gcm==0.3
-e git+https://github.com/pwdyson/inflect.py@d4e57f041394bb246d8f9c360c20c19e44eeda03#egg=inflect
iniparse==0.4
iotop==0.6
IPy==0.75
javapackages==1.0.0
kitchen==1.1.1
lxml==3.2.1
MySQL-python==1.2.5
mysqlclient==1.3.10
netifaces==0.10.4
ngxtop==0.0.2
numpy==1.5.0
oauthlib==0.7.1
olefile==0.44
PIL==1.1.7
Pillow==2.5.3
policycoreutils-default-encoding==0.1
psycopg2==2.5.4
pycrypto==2.3
pycurl==7.19.0
pygpgme==0.3
PyJWT==0.3.0
pyliblzma==0.5.3
pyparsing==1.5.6
python-gcm==0.1.5
python-openid==2.2.5
pyxattr==0.5.1
reportlab==2.4
requests==2.4.3
requests-oauthlib==0.4.2
seobject==0.1
sepolicy==1.1
six==1.10.0
suds==0.4
suds-jurko==0.6
tabulate==0.7.2
Unidecode==0.4.17
urlgrabber==3.10
virtualenv==12.0.7
yum-metadata-parser==1.1.4

This is my requirements.txt (for pip) in production (which I will change authorizesauce to .5.0 when complete)
AuthorizeSauce==0.4.1
Django==1.7
MySQL-python==1.2.5
Pillow==2.5.3
PyJWT==0.3.0
Unidecode==0.04.17
apns==2.0.1
argparse==1.2.1
django-crontab==0.6.0
django-messages-extends==0.4
djangorestframework==2.4.4
djrill==1.3.0
oauthlib==0.7.1
python-gcm==0.1.5
python-openid==2.2.5
requests==2.4.3
requests-oauthlib==0.4.2
six==1.8.0
suds==0.4
wsgiref==0.1.2

**Comment by dennben78** [comment]
DEVELOPMENT environment PIP FREEZE (I notice my django version got bumped up by something):
adium-theme-ubuntu==0.3.4
apns==2.0.1
AuthorizeSauce==0.5.0
chardet==2.2.1
Django==1.8.6
django-crontab==0.6.0
django-extensions==1.8.1
django-inspect==0.3.2
django-messages-extends==0.4
django-ssl-redirect==1.0
djangorestframework==2.4.4
djrill==1.3.0
docopt==0.6.1
docutils==0.7
gcm==0.3
inflect==0.2.5
iniparse==0.4
IPy==0.75
kitchen==1.1.1
lxml==3.8.0
MySQL-python==1.2.5
mysqlclient==1.3.10
netifaces==0.10.4
ngxtop==0.0.2
oauthlib==0.7.1
olefile==0.44
Pillow==2.5.3
pycrypto==2.3
pycurl==7.43.0
PyJWT==0.3.0
pyparsing==1.5.6
python-apt==1.1.0b5
python-gcm==0.1.5
python-openid==2.2.5
pytz==2017.2
PyXB==1.2.5
reportlab==2.4
requests==2.4.3
requests-oauthlib==0.4.2
six==1.10.0
sqlparse==0.2.3
suds==0.4
suds-jurko==0.6
tabulate==0.7.2
ubuntuone-client-data==14.4
Unidecode==0.4.17
unity-lens-photos==1.0
virtualenv==12.0.7

**Comment by ugkarthik** [comment]
Hi,

Add the SSl Header in the settings,

```SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')```

All requests should be in Https
